extensions: {}
cabal-file: project.cabal
extra-packages: ''
version: 1
environment: ghc-7.4.2-unstable
module-template: ! 'module MODULE_NAME where

'
ghc-args: []
modules:
  Main(Main.hs):
    filename: Main.hs
